service: ms-lab
provider:
  name: aws
  stage: dev
  runtime: nodejs16.x
  region: us-east-1
  httpApi:
    cors: true
functions:
  nuxt:
    handler: .output/server/index.handler
    events:
      - httpApi: '*'